name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/odoo/odoo.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync configured branches
        run: |
          echo "🔧 Syncing branches from variable: ${{ vars.SYNC_BRANCHES }}"
          for BRANCH in ${{ vars.SYNC_BRANCHES }}; do
            echo "🔁 Syncing $BRANCH..."
            git checkout $BRANCH || git checkout -b $BRANCH origin/$BRANCH
            git pull origin $BRANCH || echo "ℹ️ Pull skipped (new branch?)"
            git merge --no-ff --no-edit upstream/$BRANCH || echo "⚠️ Merge conflict in $BRANCH"
            git push origin $BRANCH
            echo "✅ Done syncing $BRANCH"
            echo ""
          done
